### ISSUE TITLE
v2.0.0: 'NotebookWebApplication' object has no attribute 'append'

### ISSUE THREAD

**Issue by robnagler** [jupyterlab/jupyterlab_server#146]
Downgrading to  jupyterlab-server==1.2.0 works. Here's the stack of the error:

```txt
jupyter lab --no-browser --port=8888 --ip=0.0.0.0
[I 23:36:06.549 LabApp] Writing notebook server cookie secret to /home/vagrant/.local/share/jupyter/runtime/notebook_cookie_secret
[I 23:36:07.049 LabApp] JupyterLab extension loaded from /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/jupyterlab
[I 23:36:07.049 LabApp] JupyterLab application directory is /home/vagrant/.pyenv/versions/3.7.2/envs/py3/share/jupyter/lab
zzzz[W 23:36:07.051 LabApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1991, in init_server_extensions
        func(self)
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/jupyterlab/extension.py", line 222, in load_jupyter_server_extension
        add_handlers(web_app, config)
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/jupyterlab_server/handlers.py", line 165, in add_handlers
        handlers.append((url_pattern, LabHandler))
    AttributeError: 'NotebookWebApplication' object has no attribute 'append'
```

**Comment by robnagler** [comment]
Thanks @blink1073! I fixed it by pinning the version in our Docker build. It was pulling in the latest independently of jupyterlab, and pip wasn't complaining (don't ask me why).

**Comment by krassowski** [comment]
Linking back to [SO post](https://stackoverflow.com/questions/67013399/jupyter-lab-404-not-found-you-are-requesting-a-page-that-does-not-exist/) with the same error message, but slightly different underlying issue in case if Google leads ussers here.
