### ISSUE TITLE
RFE: please upgrade for `mistune` 2.0.x

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab_server#310]
`jupyterlab_server` is not ready for `mistune` 2.0.x.
```console
+ /usr/bin/sphinx-build -j48 -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.2.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 274, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 401, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/__init__.py", line 13, in <module>
    from sphinxcontrib.openapi import renderers, directive
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/renderers/__init__.py", line 4, in <module>
    from ._httpdomain_old import HttpdomainOldRenderer
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/renderers/_httpdomain_old.py", line 6, in <module>
    from .. import openapi20, openapi30, utils
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/openapi20.py", line 16, in <module>
    from sphinxcontrib.openapi import utils
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/utils.py", line 20, in <module>
    from m2r import convert as convert_markdown
  File "/usr/lib/python3.8/site-packages/m2r.py", line 58, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

Exception occurred:
  File "/usr/lib/python3.8/site-packages/m2r.py", line 58, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
The full traceback has been saved in /tmp/sphinx-err-2u8k8d98.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by fcollonval** [comment]
To provide background, the error is due to `sphincontribub-openapi` that depends on `m2r` that has not been updated for `mistune` 2.

Xref: 
- [https://github.com/sphinx-contrib/openapi](https://github.com/sphinx-contrib/openapi/issues/123)
- [m2r issue](https://github.com/miyakogi/m2r/issues/66)

**Comment by kloczek** [comment]
OK closing 👍
