### ISSUE TITLE
2.16.4: sphinx fails because incorrect path to app-config.rst and `reference target not found` sphinx warnings

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab_server#350]
Looks like docs/source/ content needs some updates
```console
[tkloczko@pers-jacek jupyterlab_server-2.16.4]$ PYTHONPATH=$PWD /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.3.0
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.17.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.16.4/docs/source/conf.py", line 108, in setup
    exec(compile(f.read(), "../autogen_config.py", "exec"), {})  # noqa
  File "../autogen_config.py", line 46, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.16.4/source/api/app-config.rst'

Exception occurred:
  File "../autogen_config.py", line 46, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.16.4/source/api/app-config.rst'
The full traceback has been saved in /tmp/sphinx-err-msv5x255.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
Instead of injecting PYTHONPATH=$PWD could be applied patch like below
```patch
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -9,10 +9,10 @@
 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
-#
-# import os
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import os
+import sys
+sys.path.insert(0, os.path.abspath("../.."))
+
 import os.path as osp
 import shutil
 import sys
```
This patch does exactly what is mentioned in comment above that code.

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔

**Comment by kloczek** [comment]
Looks like below patch fixes issue
```patch
--- a/docs/autogen_config.py
+++ b/docs/autogen_config.py
@@ -41,7 +41,7 @@
 if os.path.basename(cwd) == "source":
     destination = os.path.join(cwd, "api/app-config.rst")
 else:
-    destination = os.path.join(cwd, "source/api/app-config.rst")
+    destination = os.path.join(cwd, "docs/source/api/app-config.rst")

 with open(destination, "w") as f:
     f.write(header)
```
After apply that patch I found some sphinx warnings
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.3.0
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.18.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
making output directory... done
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['html_image'], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 10 added, 0 changed, 0 removed
skipping non-JSON example generation.
skipping non-JSON example generation.
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jupyterlab-server.3 { changelog api/index api/app-config api/app api/config api/handlers api/process api/rest api/spec } /home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/docs/source/api/app-config.rst:1234: WARNING: py:meth reference target not found: WebSocketHandler.get_compression_options
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/config.py:docstring of jupyterlab_server.config.get_static_page_config:1: WARNING: py:class reference target not found: logger
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/config.py:docstring of jupyterlab_server.config.get_static_page_config:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/config.py:docstring of jupyterlab_server.config.get_static_page_config:1: WARNING: py:class reference target not found: string
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/config.py:docstring of jupyterlab_server.config.get_static_page_config:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/config.py:docstring of jupyterlab_server.config.get_static_page_config:1: WARNING: py:class reference target not found: 'all'
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/handlers.py:docstring of jupyterlab_server.handlers.LabHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/handlers.py:docstring of jupyterlab_server.handlers.LabHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/listings_handler.py:docstring of jupyterlab_server.listings_handler.ListingsHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/listings_handler.py:docstring of jupyterlab_server.listings_handler.ListingsHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_handler.py:docstring of jupyterlab_server.settings_handler.SettingsHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_handler.py:docstring of jupyterlab_server.settings_handler.SettingsHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_utils.py:docstring of jupyterlab_server.settings_utils.get_settings:1: WARNING: py:class reference target not found: schema_name
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_utils.py:docstring of jupyterlab_server.settings_utils.get_settings:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_utils.py:docstring of jupyterlab_server.settings_utils.get_settings:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/settings_utils.py:docstring of jupyterlab_server.settings_utils.get_settings:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/themes_handler.py:docstring of jupyterlab_server.themes_handler.ThemesHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/themes_handler.py:docstring of jupyterlab_server.themes_handler.ThemesHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/translations_handler.py:docstring of jupyterlab_server.translations_handler.TranslationsHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/translations_handler.py:docstring of jupyterlab_server.translations_handler.TranslationsHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/translations_handler.py:docstring of jupyterlab_server.translations_handler.TranslationsHandler.get:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/workspaces_handler.py:docstring of jupyterlab_server.workspaces_handler.WorkspacesHandler:1: WARNING: py:class reference target not found: tornado.web.Application
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/workspaces_handler.py:docstring of jupyterlab_server.workspaces_handler.WorkspacesHandler:1: WARNING: py:class reference target not found: tornado.httputil.HTTPServerRequest
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/workspaces_handler.py:docstring of jupyterlab_server.workspaces_handler.WorkspacesHandler.initialize:1: WARNING: py:class reference target not found: jupyterlab_server.workspaces_handler.WorkspacesManager
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/process.py:docstring of jupyterlab_server.process.Process.wait:1: WARNING: py:class reference target not found: The process exit code.
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/process.py:docstring of jupyterlab_server.process.which:1: WARNING: py:class reference target not found: optional
/home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.17.0/jupyterlab_server/spec.py:docstring of jupyterlab_server.spec.get_openapi_spec:1: WARNING: py:class reference target not found: Spec
done
build succeeded, 27 warnings.
```

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/frostming/unearth/issues/14
https://github.com/pypa/distlib/commit/98b9b89f

**Comment by blink1073** [comment]
We run the docs from the docs folder, both in CI and in RTD, we don't support running it from the root folder.

**Comment by kloczek** [comment]
Is it not would be better to merge somehow docs/autogen_config.py with docs/source/conf.py? 🤔 
`sphinx-build` command always changes current directory to location where is conf.py file.

**Comment by kloczek** [comment]
Thank you 👍 
What about nitpick warnings? 🤔 
I'm not affected by those issue because I'm only interested in generate man page however in html output instead links are only highlighted keywords.

**Comment by blink1073** [comment]
I don't think we want to go down the path of handling nitpick errors, there are a lot of false positives for things like `TYPE_CHECKING` guards on classes that are used in function signatures.
