### ISSUE TITLE
2.20.0: pytest is failing in `tests/test_process.py::test_process_app` unit

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab_server#386]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

Here is pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-jupyterlab-server-2.20.0-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-jupyterlab-server-2.20.0-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
============================= test session starts ==============================
platform linux -- Python 3.8.16, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.20.0, configfile: pyproject.toml, testpaths: tests/
plugins: anyio-3.6.2, requests-mock-1.10.0, console-scripts-1.3.1, timeout-2.1.0
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 143 items

tests/test_config.py .                                                   [  0%]
tests/test_labapp.py ......                                              [  4%]
tests/test_licenses_api.py ............................................. [ 36%]
........................................                                 [ 64%]
tests/test_listings_api.py ..                                            [ 65%]
tests/test_process.py ...F                                               [ 68%]
tests/test_settings_api.py .............                                 [ 77%]
tests/test_themes_api.py ..                                              [ 79%]
tests/test_translation_api.py .................                          [ 90%]
tests/test_translation_utils.py ....                                     [ 93%]
tests/test_workspaces_api.py ........                                    [ 99%]
tests/test_workspaces_app.py .                                           [100%]

=================================== FAILURES ===================================
_______________________________ test_process_app _______________________________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7fd157186430>
when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.

        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/usr/lib/python3.8/site-packages/_pytest/runner.py:339:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/site-packages/_pytest/runner.py:260: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/usr/lib/python3.8/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
/usr/lib/python3.8/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6>
E
E               Traceback (most recent call last):
E                 File "/usr/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2371, in init_httpserver
E                   self._find_http_port()
E               ResourceWarning: unclosed <socket.socket fd=20, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 8888, 0, 0)>

/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
----------------------------- Captured stdout call -----------------------------
Python 3.8.16
----------------------------- Captured stderr call -----------------------------
[I 2023-03-15 14:15:54.723 ServerApp] tests | extension was successfully linked.
[W 2023-03-15 14:15:54.738 ServerApp] tests | extension failed loading with message: ExtensionLoadingError('_load_jupyter_server_extension function was not found.')
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 356, in load_extension
        extension.load_all_points(self.serverapp)
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 228, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 228, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 219, in load_point
        return point.load(serverapp)
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 146, in load
        loader = self._get_loader()
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 115, in _get_loader
        loader = get_loader(loc)
      File "/usr/lib/python3.8/site-packages/jupyter_server/extension/utils.py", line 47, in get_loader
        raise ExtensionLoadingError(msg) from None
    jupyter_server.extension.utils.ExtensionLoadingError: _load_jupyter_server_extension function was not found.
[I 2023-03-15 14:15:54.744 ServerApp] Serving notebooks from local directory: /home/tkloczko/rpmbuild/BUILD/jupyterlab_server-2.20.0
[I 2023-03-15 14:15:54.744 ServerApp] Jupyter Server 2.4.0 is running at:
[I 2023-03-15 14:15:54.744 ServerApp] http://localhost:8888/?token=4b4031a206b4f81358a41e739f6214b63c1e91fd53c01bf8
[I 2023-03-15 14:15:54.745 ServerApp]     http://127.0.0.1:8888/?token=4b4031a206b4f81358a41e739f6214b63c1e91fd53c01bf8
[I 2023-03-15 14:15:54.745 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-03-15 14:15:54.748 ServerApp]

    To access the server, open this file in a browser:
        file:///home/tkloczko/.local/share/jupyter/runtime/jpserver-1521171-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=4b4031a206b4f81358a41e739f6214b63c1e91fd53c01bf8
        http://127.0.0.1:8888/?token=4b4031a206b4f81358a41e739f6214b63c1e91fd53c01bf8
[I 2023-03-15 14:15:54.750 TestApp] > /usr/bin/python3 --version
--------------------------- Captured stderr teardown ---------------------------
[I 2023-03-15 14:15:55.920 ServerApp] Shutting down 1 extension
=============================== warnings summary ===============================
tests/test_listings_api.py: 1 warning
tests/test_settings_api.py: 8 warnings
tests/test_translation_api.py: 5 warnings
tests/test_workspaces_api.py: 4 warnings
  /usr/lib/python3.8/site-packages/openapi_schema_validator/validators.py:113: DeprecationWarning: read property is deprecated. Use OAS30ReadValidator instead.
    warnings.warn(

tests/test_settings_api.py: 7 warnings
tests/test_themes_api.py: 1 warning
tests/test_translation_api.py: 4 warnings
tests/test_workspaces_api.py: 3 warnings
  /usr/lib/python3.8/site-packages/openapi_schema_validator/validators.py:120: DeprecationWarning: write property is deprecated. Use OAS30WriteValidator instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 10 durations =============================
4.84s setup    tests/test_translation_api.py::test_get
2.02s call     tests/test_process.py::test_process
1.08s call     tests/test_process.py::test_process_app
1.01s teardown tests/test_translation_api.py::test_get_display_name_invalid
0.47s call     tests/test_settings_api.py::test_patch
0.16s call     tests/test_settings_api.py::test_listing
0.11s call     tests/test_settings_api.py::test_patch_unicode
0.10s setup    tests/test_labapp.py::test_lab_handler
0.10s setup    tests/test_listings_api.py::test_get_listing
0.08s setup    tests/test_licenses_api.py::test_get_license_report[mime_format_parser0-True--false-False]
=========================== short test summary info ============================
FAILED tests/test_process.py::test_process_app - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.sock...
================= 1 failed, 142 passed, 33 warnings in 16.30s ==================
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.13
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.2.1
attrs                         22.2.0
autodoc-traits                0.1.0
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
build                         0.10.0
cffi                          1.15.1
charset-normalizer            3.1.0
comm                          0.1.2
debugpy                       1.6.6
decorator                     5.1.1
deepmerge                     1.1.0
defusedxml                    0.7.1
deprecation                   2.1.0
distro                        1.8.0
docutils                      0.19
editables                     0.3
entrypoints                   0.4
exceptiongroup                1.0.0
executing                     1.2.0
fastjsonschema                2.16.3
gpg                           1.18.0-unknown
hatchling                     1.13.0
html5lib                      1.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.12.0
iniconfig                     2.0.0
ipykernel                     6.21.3
ipython                       8.6.0
isodate                       0.6.1
jedi                          0.18.2
Jinja2                        3.1.2
json5                         0.9.12
jsonschema                    4.17.3
jsonschema-spec               0.1.3
jupyter_client                8.0.3
jupyter_core                  5.2.0
jupyter-events                0.6.3
jupyter_packaging             0.12.3
jupyter_server                2.4.0
jupyter_server_terminals      0.4.4
jupyterlab-pygments           0.1.2
lazy-object-proxy             1.9.0
libcomps                      0.1.19
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.5
mdurl                         0.1.2
mistune                       2.0.5
more-itertools                9.1.0
myst-parser                   0.19.1
nbclient                      0.7.2
nbconvert                     7.2.10
nbformat                      5.7.3
nest-asyncio                  1.5.6
numpydoc                      1.5.0
openapi-core                  0.16.6
openapi-schema-validator      0.4.3
openapi-spec-validator        0.5.5
packaging                     23.0
pandocfilters                 1.5.0
parse                         1.19.0
parso                         0.8.3
pathable                      0.4.3
pathspec                      0.11.0
pexpect                       4.8.0
pickleshare                   0.7.5
picobox                       2.2.0
pip                           22.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  3.1.1
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.16.0
prompt-toolkit                3.0.38
psutil                        5.9.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.14.0
pyproject_hooks               1.0.0
pyrsistent                    0.19.3
pytest                        7.2.2
pytest-console-scripts        1.3.1
pytest-jupyter                0.6.2
pytest-timeout                2.1.0
python-dateutil               2.8.2
python-json-logger            2.0.7
pytz                          2022.4
PyYAML                        6.0
pyzmq                         24.0.1
requests                      2.28.2
requests-mock                 1.10.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpm                           4.17.0
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
Send2Trash                    1.8.0
setuptools                    65.6.3
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
soupsieve                     2.4
Sphinx                        6.1.3
sphinx-copybutton             0.5.1
sphinx_mdinclude              0.5.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2.dev20230202
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-httpdomain      1.8.0
sphinxcontrib-jsmath          1.0.1.dev20230128
sphinxcontrib-openapi         0.8.1
sphinxcontrib-qthelp          1.0.3.dev20230128
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
strict-rfc3339                0.7
terminado                     0.17.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.8.1
typing_extensions             4.5.0
urllib3                       1.26.15
wcwidth                       0.2.6
webencodings                  0.5.1
websocket-client              1.5.1
Werkzeug                      2.2.3
wheel                         0.38.4
zipp                          3.15.0
```
</details>

**Comment by kloczek** [comment]
Closing. Last version nolonger fails that way.
